<?php

/**
 * @file
 * Contains group_solr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function group_solr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_solr module.
    case 'help.page.group_solr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module add Solr indexed field(s) which is determined access control with 
        <a href="https://www.drupal.org/project/group" target="_blank">Group</a> 
        for an indexed item to be public or private for annonymous users') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function group_solr_theme() {
  return [
    'group_solr' => [
      'render element' => 'children',
    ],
  ];
}
