<?php

/**
 * @file
 * Contains group_solr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function group_solr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_solr module.
    case 'help.page.group_solr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module add Solr indexed field(s) which is determined access control with 
        <a href="https://www.drupal.org/project/group" target="_blank">Group</a> 
        for an indexed item to be public or private for annonymous users') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function group_solr_theme() {
  return [
    'group_solr' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_views_query_alter
 * @param $view
 * @param $query
 * @return void
 */
function group_solr_views_query_alter($view, $query) {
  if ($view->id() == 'solr_search_content') {
    // Get current user
    $uid = \Drupal::currentUser()->id();
    $current_user = \Drupal\user\Entity\User::load($uid);

    // Get groups which this user is belonged to
    $groups = array();
    $grp_membership_service = \Drupal::service('group.membership_loader');
    $grps = $grp_membership_service->loadByUser($current_user);
    foreach ($grps as $grp) {
      $groups[$grp->getGroup()->id()] = $grp->getGroup()->label();
    }

    if (count($groups) > 0) {
      // - from those group, get the taxonomy term in field_access_terms
      // - from those terms, get term ids
      $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree("islandora_access");
      $conditions = $query->createConditionGroup('OR');
      $conditions->addCondition("group_access_control", '200', "=");
      foreach ($terms as $term) {
        if (in_array($term->name, $groups)) {
          $conditions->addCondition('group_access_control', $term->name, "IN");
        }
      }
      $query->addConditionGroup($conditions);
    }
    else {
      $query->addCondition('group_access_control', "200", '=');
    }
  }
}
